//@@@@@@@@@@@@@@@@@@@@@@@@@@@@ USUARIOS

GET http://localhost:4000/api/usuarios/

###

POST http://localhost:4000/api/usuarios
content-type: application/json

{   
    "nombre": "Ronaldinho",
    "apellido": "Soccer",
    "edad": 35,
    "telefono": 7278875,
    "correo": "ronaldinhosoccerhaha@gmail.com"
}

###

DELETE http://localhost:4000/api/usuarios/64794fcef19f1303bc3b86f4

###

PUT http://localhost:4000/api/usuarios/64791d6a2ff9a80640039af9
content-type: application/json

{   
    "nombre": "Cristiano",
    "apellido": "Soccer",
    "edad": 30,
    "telefono": 1234567,
    "correo": "holi@gmail.com"
}


###
//@@@@@@@@@@@@@@@@@@@@@@@@@@@@ RECARGAS

GET http://localhost:4000/api/recargas/

###

POST http://localhost:4000/api/recargas
content-type: application/json

{   
    "idComprador": "String",
    "montoRecarga": 20,
    "paisRecarga": "AR",
    "companiaRecarga": "String",
    "estadoRecarga": "String"

}

###

DELETE http://localhost:4000/api/recargas/647abef33554ccd8c8495859

###

PUT http://localhost:4000/api/recargas/647abef33554ccd8c8495859
content-type: application/json

{   
    "idComprador": "String",
    "montoRecarga": 20000,
    "paisRecarga": "AR",
    "companiaRecarga": "String",
    "estadoRecarga": "String"
}
